export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const RESET = "RESET";
export const INCREMENT_BY_AMOUNT = "INCREMENT_BY_AMOUNT";
export const HANDLE_ACTIVE = "HANDLE_ACTIVE";
export const HANDLE_OPEN_CART = "HANDLE_OPEN_CART";
export const HANDLE_OPEN_MENU = "HANDLE_OPEN_MENU";
